ALTER TABLE data DROP COLUMN IF EXISTS temperature;
ALTER TABLE data ADD COLUMN temperature DOUBLE NULL;
ALTER TABLE data DROP COLUMN IF EXISTS soil;
ALTER TABLE data ADD COLUMN soil DOUBLE NULL;
ALTER TABLE data DROP COLUMN IF EXISTS water_high;
ALTER TABLE data ADD COLUMN water_high BOOLEAN NULL;
ALTER TABLE data DROP COLUMN IF EXISTS water_low;
ALTER TABLE data ADD COLUMN water_low BOOLEAN NULL;