ALTER TABLE data DROP COLUMN IF EXISTS temperature;
ALTER TABLE data ADD COLUMN temperature DOUBLE DEFAULT 0;
ALTER TABLE data DROP COLUMN IF EXISTS soil;
ALTER TABLE data ADD COLUMN soil DOUBLE DEFAULT 0;
ALTER TABLE data DROP COLUMN IF EXISTS water_high;
ALTER TABLE data ADD COLUMN water_high BOOLEAN DEFAULT false;
ALTER TABLE data DROP COLUMN IF EXISTS water_low;
ALTER TABLE data ADD COLUMN water_low BOOLEAN DEFAULT false;